### ISSUE TITLE
Ability to get commit type map from external package

### ISSUE THREAD

**Issue by mrfelton** [BublTechnology/customizable-commit-analyzer#8]
Similar to how https://github.com/kentcdodds/validate-commit-msg#types lets you provide the name to an external package where a list of commit types is defined, it would be a good if this package supported something similar so that you could reference in `commitTypeMap` from an external package. This would save a lot of duplication and help ensure consistency when using with multiple projects.

ie, rather than having to do this every time:

```
  "config": {
    "commitTypeMap": {
      "feat": "minor",
      "fix": "patch",
      "docs": "patch",
      "style": "patch",
      "refactor": "patch",
      "perf": "patch",
      "test": "patch",
      "build": "patch",
      "ci": "patch",
      "chore": "patch",
      "revert": "patch"
    },
  }
```

we could instead do something like:

```
  "config": {
    "commitTypeMap": "conventional-commit-type-map",
  }
```

(where `conventional-commit-type-map` is the name of a package that exports an object to be used as `commitTypeMap`

**Comment by turbobeast** [comment]
makes sense. as long as it falls back. and i think the `map` would have to be the default export of whatever package is provided.
